spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
  springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
      path: /swagger-ui.html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #  sql:
#    init:
#      data-locations: classpath:database/data.sql # 더미데이터 파일 연결
#      mode: always
#      platform: h2
  file:
    dir: 'file:/Users/Kimjuchan/Desktop/Hanbat_Market_FIle/'