-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgz4ebPSRt2DdFeCvY
n5jNAHAdbkBJ//oAWsAaz5YAU86gCgYIKoZIzj0DAQehRANCAATnmiCidohzBQJf
bCrI61fmXsiS4LZJUtx2Qsk5+Pmkcb91pAzYsyPo5B4AnB8e/rYg9nF6EkMMPEgE
VYIwZEj4
-----END PRIVATE KEY-----